### ISSUE TITLE
Low battery notification error

### ISSUE THREAD

**Issue by gromar88** [bieniu/home-assistant-config#12]
One of my device shows Unknown state as a battery level. 
My notification about it looks like that:
```
- id: notification_low_battery
  alias: Notification Low Battery
  description: powiadom o niskim poziomie naładowania baterii
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: template
    value_template: "{% macro battery_level() %}\n  {% for item in states['sensor']\
      \ if item.attributes.device_class == 'battery' and item.attributes.unit_of_measurement\
      \ == '%' and item.state | int(0) < threshold %}\n    {{ item.entity_id }}\n\
      \  {% endfor %}\n{% endmacro %} {{ battery_level() | trim != '' }}\n"
  action:
  - service: python_script.notify
    data:
      title: Niski poziom naładowania baterii
      message: '{% macro battery_level() %}{% for item in states[''sensor''] if item.attributes.device_class
        == ''battery'' and item.attributes.unit_of_measurement == ''%'' and item.state
        | int(0) < threshold %}<br> - {{ device_attr(item.entity_id, ''name_by_user'')
        }}{% if area_name(item.entity_id) %}, {{ area_name(item.entity_id) }}{% endif
        %} [{{ item.state | round(0, ''unknown'') }}%]{% endfor %}{% endmacro %} W
        następujących urządzeniach jest niski poziom naładowania baterii: {{ battery_level()
        }}'
      tag: notification-low-battery
      group: other
      services:
      - service: notify.mobile_app_marcin_phone
        type: android
  variables:
    threshold: 20
```

Each time when I run this automation I got error:
```
Logger: homeassistant.components.automation.notification_low_battery
Source: components/automation/__init__.py:525
Integration: Automatyzacja ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 21:37:50 (1 occurrences)
Last logged: 21:37:50

Error while executing automation automation.notification_low_battery: Error rendering data template: ValueError: Template error: round got invalid input 'unknown' when rendering template '{% macro battery_level() %}{% for item in states['sensor'] if item.attributes.device_class == 'battery' and item.attributes.unit_of_measurement == '%' and item.state | int(0) < threshold %}<br> - {{ device_attr(item.entity_id, 'name_by_user') }}{% if area_name(item.entity_id) %}, {{ area_name(item.entity_id) }}{% endif %} [{{ item.state | round(0, 'unknown') }}%]{% endfor %}{% endmacro %} W następujących urządzeniach jest niski poziom naładowania baterii: {{ battery_level() }}' but no default was specified
```

Thank you in advance for any help!
